spring.application.name=scac-back
server.port=8888

# JPA 설정
# update : 변경된 컬럼 추가(기존 데이터 유지)
# create : 매번 재생성(기존 데이터 삭제)
# none: 아무것도 하지 않음 (운영 환경 권장)
spring.jpa.hibernate.ddl-auto=update

# 실행 SQL 콘솔 출력(작업용, 운영할때는 false)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=${JWT_SECRET}
jwt.access-expiration=1800000
jwt.refresh-expiration=604800000

# MyBatis Setting
# MyBatis Mapper Locations
mybatis.mapper-locations=classpath:mappers/**/*.xml
# MyBatis Aliase 
# mybatis.type-aliases-package=com.scac.dto
# MyBatis Configuration underbars to camelCase
mybatis.configuration.map-underscore-to-camel-case=true

# import .env
spring.config.import=optional:file:.env[.properties]

# FrontEnd URL (Redirect URL)
app.frontend-url=http://localhost:3000,http://localhost:3001
